import { refinePromptWithLLM } from './src/services/promptRefinementService.js';
import dotenv from 'dotenv';
dotenv.config();

async function main() {
    const payload = {
        title: 'how to learn web dev in 2026',
        topic: 'how to learn web dev in 2026',
        keywords: 'web dev, programming, learning, 2026',
        niche: 'tech',
        archetype: 'hero',
        aspectRatio: '16:9',
        learningModifiers: '',
        usePhoto: false
    };
    
    try {
        console.log('Generating prompt with Gemini...');
        const prompt = await refinePromptWithLLM(payload);
        console.log('\n--- EXACT PROMPT GENERATED BY GEMINI API ---');
        console.log(prompt);
        console.log('---------------------------------------------');
    } catch (e) {
        console.error('Error:', e);
    }
}

main();
